# Map environment variables used in NestJS backend to Quarkus properties
frontend.url=${FRONTEND_URL:}
main.url=${MAIN_URL:}
security.not-secured=${NOT_SECURED:false}
api.limit=${API_LIMIT:30}
quarkus.http.port=${PORT:3000}
